stages:
- stage: build
  displayName: Build
  jobs:
  - job: build_sdist
    displayName: Source Dist
    pool:
      vmImage: vs2017-win2016
    steps:
    - checkout: self
      fetchDepth: 1
      submodules: true
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
    - pwsh: |
        python -mpip install -U setuptools
        python -mpip install -r requirements.txt
    - pwsh: |
        $files = git ls-files --recurse-submodules
        $manifest = ""
        foreach ($file in $files) {
          $manifest += "include $file`n"
        }
        Set-Content MANIFEST.in $manifest
    - task: PythonScript@0
      inputs:
        scriptSource: filePath
        scriptPath: setup.py
        arguments: sdist --formats=zip
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: sdist
        targetPath: dist
  - job: build_cp_win
    displayName: Wheel Windows
    strategy:
      matrix:
        CPython36 x86:
          PYTHON_VERSION: '3.6'
          PYTHON_ARCH: x86
        CPython37 x86:
          PYTHON_VERSION: '3.7'
          PYTHON_ARCH: x86
        CPython36 x64:
          PYTHON_VERSION: '3.6'
          PYTHON_ARCH: x64
        CPython37 x64:
          PYTHON_VERSION: '3.7'
          PYTHON_ARCH: x64
    pool:
      vmImage: vs2017-win2016
    steps:
    - checkout: self
      fetchDepth: 1
      submodules: true
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(PYTHON_VERSION)
        architecture: $(PYTHON_ARCH)
    - pwsh: |
        python -mpip install -U setuptools wheel
        python -mpip install -r requirements.txt
    - task: PythonScript@0
      inputs:
        scriptSource: filePath
        scriptPath: setup.py
        arguments: bdist_wheel
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: wheel cp$(PYTHON_VERSION)-win_$(PYTHON_ARCH)
        targetPath: dist
  - job: build_cp_linux
    displayName: Wheel Linux
    container:
      image: quay.io/pypa/manylinux2010_x86_64
    steps:
    - checkout: self
      fetchDepth: 1
      submodules: true
    - bash: /opt/python/cp36-cp36m/bin/python -mpip install -r requirements.txt --user
    - task: PythonScript@0
      inputs:
        scriptSource: filePath
        scriptPath: setup.py
        arguments: bdist_wheel --py-limited-api cp36
        pythonInterpreter: /opt/python/cp36-cp36m/bin/python
    - bash: |
        auditwheel show dist/*.whl
        auditwheel repair dist/*.whl
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: wheel cp-linux_x64
        targetPath: wheelhouse
  - job: build_cp_macos
    displayName: Wheel macOS
    pool:
      vmImage: macOS-10.14
    steps:
    - checkout: self
      fetchDepth: 1
      submodules: true
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
    - pwsh: |
        python -mpip install -U setuptools wheel --user
        python -mpip install -r requirements.txt --user
    - task: PythonScript@0
      inputs:
        scriptSource: filePath
        scriptPath: setup.py
        arguments: bdist_wheel --py-limited-api cp36
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: wheel cp-macos_x64
        targetPath: dist
- stage: test
  displayName: Test
  jobs:
  - job: test_windows
    displayName: Windows
    strategy:
      matrix:
        CPython36 x86:
          PYTHON_VERSION: '3.6'
          PYTHON_ARCH: x86
        CPython37 x86:
          PYTHON_VERSION: '3.7'
          PYTHON_ARCH: x86
        CPython36 x64:
          PYTHON_VERSION: '3.6'
          PYTHON_ARCH: x64
        CPython37 x64:
          PYTHON_VERSION: '3.7'
          PYTHON_ARCH: x64
    pool:
      vmImage: vs2017-win2016
    steps:
    - checkout: self
      fetchDepth: 1
    - task: CopyFiles@2
      inputs:
        sourceFolder: $(Build.SourcesDirectory)
        content: tests
        targetFolder: $(Agent.BuildDirectory)
    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: wheel cp$(PYTHON_VERSION)-win_$(PYTHON_ARCH)
        downloadPath: $(Agent.BuildDirectory)
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(PYTHON_VERSION)
        architecture: $(PYTHON_ARCH)
    - pwsh: |
        python -mpip install -U setuptools wheel codecov
        python -mpip install pytest pytest-cov
    - pwsh: python -mpip install (Get-ChildItem ffilupa-*.whl)
      workingDirectory: $(Agent.BuildDirectory)
    - pwsh: python -mpytest --rootdir=. --cov=ffilupa --cov-report=xml --junitxml=junit\test-results.xml
      workingDirectory: $(Agent.BuildDirectory)\tests
    - task: PublishTestResults@2
      inputs:
        searchFolder: $(Agent.BuildDirectory)\tests
        testResultsFiles: junit\test-results.xml
      condition: succeededOrFailed()
    - pwsh: codecov -t 4d08d9aa-a2cc-4c5d-9511-94a89b59c3f0 -f ..\tests\coverage.xml
      condition: succeededOrFailed()
  - job: test_linux
    displayName: Linux
    strategy:
      matrix:
        CPython36:
          PYTHON_VERSION: '3.6'
        CPython37:
          PYTHON_VERSION: '3.7'
    pool:
      vmImage: ubuntu-16.04
    steps:
    - checkout: self
      fetchDepth: 1
    - task: CopyFiles@2
      inputs:
        sourceFolder: $(Build.SourcesDirectory)
        content: tests
        targetFolder: $(Agent.BuildDirectory)
    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: wheel cp-linux_x64
        downloadPath: $(Agent.BuildDirectory)
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(PYTHON_VERSION)
    - pwsh: |
        python -mpip install -U setuptools wheel codecov
        python -mpip install pytest pytest-cov
    - pwsh: python -mpip install (Get-ChildItem ffilupa-*.whl)
      workingDirectory: $(Agent.BuildDirectory)
    - pwsh: python -mpytest --rootdir=. --cov=ffilupa --cov-report=xml --junitxml=junit/test-results.xml
      workingDirectory: $(Agent.BuildDirectory)/tests
    - task: PublishTestResults@2
      inputs:
        searchFolder: $(Agent.BuildDirectory)/tests
        testResultsFiles: junit/test-results.xml
      condition: succeededOrFailed()
    - pwsh: codecov -t 4d08d9aa-a2cc-4c5d-9511-94a89b59c3f0 -f ../tests/coverage.xml
      condition: succeededOrFailed()
  - job: test_macos
    displayName: macOS
    strategy:
      matrix:
        CPython36:
          PYTHON_VERSION: '3.6'
        CPython37:
          PYTHON_VERSION: '3.7'
    pool:
      vmImage: macOS-10.14
    steps:
    - checkout: self
      fetchDepth: 1
    - task: CopyFiles@2
      inputs:
        sourceFolder: $(Build.SourcesDirectory)
        content: tests
        targetFolder: $(Agent.BuildDirectory)
    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: wheel cp-macos_x64
        downloadPath: $(Agent.BuildDirectory)
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(PYTHON_VERSION)
    - pwsh: |
        python -mpip install -U setuptools wheel codecov
        python -mpip install pytest pytest-cov
    - pwsh: python -mpip install (Get-ChildItem ffilupa-*.whl)
      workingDirectory: $(Agent.BuildDirectory)
    - pwsh: python -mpytest --rootdir=. --cov=ffilupa --cov-report=xml --junitxml=junit/test-results.xml
      workingDirectory: $(Agent.BuildDirectory)/tests
    - task: PublishTestResults@2
      inputs:
        searchFolder: $(Agent.BuildDirectory)/tests
        testResultsFiles: junit/test-results.xml
      condition: succeededOrFailed()
    - pwsh: codecov -t 4d08d9aa-a2cc-4c5d-9511-94a89b59c3f0 -f ../tests/coverage.xml
      condition: succeededOrFailed()
  - job: test_pypy
    displayName: Linux PyPy
    container:
      image: pypy:3.6
    steps:
    - checkout: self
      fetchDepth: 1
    - task: CopyFiles@2
      inputs:
        sourceFolder: $(Build.SourcesDirectory)
        content: tests
        targetFolder: $(Agent.BuildDirectory)
    - task: DownloadPipelineArtifact@1
      inputs:
        artifactName: sdist
        downloadPath: $(Agent.BuildDirectory)
    - bash: |
        pypy3 -mpip install -U setuptools wheel --user
        pypy3 -mpip install pytest --user
        pypy3 -mpip install -r requirements.txt --user
    - bash: pypy3 -mpip install ffilupa-*.zip --user
      workingDirectory: $(Agent.BuildDirectory)
    - bash: pypy3 -mpytest --rootdir=. --junitxml=junit/test-results.xml
      workingDirectory: $(Agent.BuildDirectory)/tests
    - task: PublishTestResults@2
      inputs:
        searchFolder: $(Agent.BuildDirectory)/tests
        testResultsFiles: junit/test-results.xml
      condition: succeededOrFailed()
